### ISSUE TITLE
more verbose location spotting

### ISSUE THREAD

**Issue by Snap252** [Indoqa/cycle-maven-plugin#1]
first of all: **nice work - thanks** - I even thought I have some tools to detect the cycles, but they were not able to find the issues that your plugin found.

when executing `mvn clean compile cycle:analyze` I am having that console output:

	[ERROR] Failed to execute goal com.indoqa:cycle-maven-plugin:2.0.2:analyze (default-cli) on project db:
	[ERROR] Detected package cycle:
	[ERROR] x.general.object
	[ERROR] x.data.general
	[ERROR] x.general.object

it would be pretty nice to know from what file(s) the package reference was done, so I will not have to search each file in the package manually.

maybe the above output could be:

	[ERROR] Failed to execute goal com.indoqa:cycle-maven-plugin:2.0.2:analyze (default-cli) on project db:
	[ERROR] Detected package cycle:
	[ERROR] x.general.object [class X]
	[ERROR] x.data.general [class Y, class Z]
	[ERROR] x.general.object

**Comment by stevendolg** [comment]
Hello and thanks for writing.

The list of involved classes can be quite long, so we decided against writing it directly to the console.
However a file describing all detected cycles and the involved classes should be generated and its path written directly underneath the lines you copied:

    [ERROR] Failed to execute goal com.indoqa:cycle-maven-plugin:2.0.0:analyze (default-cli) on project indoqa-fsa:
    [ERROR] Detected package cycle:
    [ERROR]     com.indoqa.fsa.cycle.a
    [ERROR]     com.indoqa.fsa.cycle.b
    [ERROR]     com.indoqa.fsa.cycle.a
    [ERROR]
    [ERROR] See /mnt/c/work/indoqa/open-source/indoqa-fsa/target/cycles.txt for involved classes.


Inside that file you should find something like this

    Cycle
      com.indoqa.fsa.cycle.a
      com.indoqa.fsa.cycle.b
      com.indoqa.fsa.cycle.a

      Involved Classes From Each Package
        com.indoqa.fsa.cycle.a
          com.indoqa.fsa.cycle.a.A -> com.indoqa.fsa.cycle.b.B

        com.indoqa.fsa.cycle.b
          com.indoqa.fsa.cycle.b.C -> com.indoqa.fsa.cycle.a.A

I hope that's what you were looking for.
